# Hypothesis using matrix

| $$X_1$$ | $$X_1$$ | $$X_3$$ | $$Y$$ |
|:-------:|:-------:|:-------:|:-----:|
|73       |80       |75       |152    |        
|93       |88       |93       |185    |
|89       |91       |90       |180    | 
|96       |98       |100      |196    |  
|73       |66       |70       |142    |

$$ H(x_{1},x_{2},x_{3}) = x_{1}w_{1} + x_{2}w_{2} + x_{3}w_{3}
$$

## python codes :

In [54]:
import tensorflow as tf
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [55]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [45]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

### hypothesis
$$ H(x_{1},x_{2},x_{3}) = x_{1}w_{1} + x_{2}w_{2} + x_{3}w_{3}
$$

In [46]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
print(hypothesis)

Tensor("add_14:0", dtype=float32)


In [47]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [53]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  1226.61 
Prediction:
 [ 188.71263123  217.09707642  218.86349487  238.30435181  163.33016968]
10 Cost:  23.7354 
Prediction:
 [ 158.01478577  180.23576355  182.52511597  198.73455811  135.22155762]
20 Cost:  23.5988 
Prediction:
 [ 157.90338135  180.13699341  182.4095459   198.61045837  135.1534729 ]
30 Cost:  23.4739 
Prediction:
 [ 157.884552    180.14938354  182.40356445  198.60571289  135.17019653]
40 Cost:  23.3497 
Prediction:
 [ 157.86605835  180.16207886  182.39793396  198.60133362  135.18710327]
50 Cost:  23.2263 
Prediction:
 [ 157.84762573  180.17474365  182.39233398  198.59698486  135.20397949]
60 Cost:  23.1034 
Prediction:
 [ 157.82923889  180.18736267  182.38671875  198.59262085  135.22080994]
70 Cost:  22.9812 
Prediction:
 [ 157.81091309  180.19996643  182.38113403  198.58828735  135.2375946 ]
80 Cost:  22.8597 
Prediction:
 [ 157.79263306  180.21253967  182.37557983  198.58395386  135.2543335 ]
90 Cost:  22.7388 
Prediction:
 [ 157.7743988   180.22506714  182

1010 Cost:  14.0033 
Prediction:
 [ 156.2928772   181.24342346  181.91955566  198.22665405  136.63037109]
1020 Cost:  13.9302 
Prediction:
 [ 156.2787323   181.25314331  181.91525269  198.22325134  136.64338684]
1030 Cost:  13.8575 
Prediction:
 [ 156.26463318  181.2628479   181.91098022  198.21986389  136.65637207]
1040 Cost:  13.7852 
Prediction:
 [ 156.25057983  181.27255249  181.90672302  198.2164917   136.66931152]
1050 Cost:  13.7133 
Prediction:
 [ 156.23654175  181.28219604  181.90246582  198.21310425  136.68222046]
1060 Cost:  13.6418 
Prediction:
 [ 156.22254944  181.29179382  181.89819336  198.20973206  136.69508362]
1070 Cost:  13.5707 
Prediction:
 [ 156.20860291  181.30140686  181.89396667  198.20637512  136.70791626]
1080 Cost:  13.4999 
Prediction:
 [ 156.19467163  181.31095886  181.88972473  198.20303345  136.72071838]
1090 Cost:  13.4295 
Prediction:
 [ 156.18080139  181.32051086  181.88552856  198.19970703  136.73350525]
1100 Cost:  13.3596 
Prediction:
 [ 156.166976

2000 Cost:  8.38556 
Prediction:
 [ 155.06439209  182.08850098  181.54679871  197.92852783  137.76341248]


# Matrix

학습데이터가 많아질 시 스파게티 코드가 되기때문에
매트릭스 사용

$
\left({\begin{array}{c} x_{1} & x_{2} & x_{3} \end{array}}\right)
*
\left(\begin{array}{c} w_{1} \\ w_{2} \\ w_{3} \end{array}\right)
=
\left({\begin{array}{c} x_{1}w_{1} + x_{2}w_{2} + x_{3}w_{3} \end{array}}\right)
$

$H(X) = XW$

## python codes :

In [78]:
import tensorflow as tf
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]

y_data = [[152.], [185.], [180.], [196.], [142.]]

In [85]:
X = tf.placeholder(tf.float32, shape=[None, 3]) #None = data의 갯수가 얼마든지 들어올수 있음
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [80]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

### hypothesis
$$ H(x_{1},x_{2},x_{3}) = x_{1}w_{1} + x_{2}w_{2} + x_{3}w_{3}
$$

In [81]:
hypothesis = tf.matmul(X, W) + b

In [82]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [83]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [84]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  7990.88 
Prediction:
 [[ 76.23345947]
 [ 86.47385406]
 [ 87.75216675]
 [ 96.32037354]
 [ 64.14930725]]
10 Cost:  11.7769 
Prediction:
 [[ 155.24002075]
 [ 181.45767212]
 [ 181.32899475]
 [ 198.22415161]
 [ 136.60317993]]
20 Cost:  11.6452 
Prediction:
 [[ 155.46653748]
 [ 181.75370789]
 [ 181.6083374 ]
 [ 198.52931213]
 [ 136.83409119]]
30 Cost:  11.587 
Prediction:
 [[ 155.45472717]
 [ 181.76319885]
 [ 181.60540771]
 [ 198.52709961]
 [ 136.84643555]]
40 Cost:  11.529 
Prediction:
 [[ 155.44221497]
 [ 181.77180481]
 [ 181.60163879]
 [ 198.52394104]
 [ 136.858078  ]]
50 Cost:  11.4713 
Prediction:
 [[ 155.42976379]
 [ 181.78041077]
 [ 181.59785461]
 [ 198.52079773]
 [ 136.8697052 ]]
60 Cost:  11.4139 
Prediction:
 [[ 155.41731262]
 [ 181.78897095]
 [ 181.59410095]
 [ 198.51765442]
 [ 136.88130188]]
70 Cost:  11.3569 
Prediction:
 [[ 155.40492249]
 [ 181.79750061]
 [ 181.59034729]
 [ 198.51451111]
 [ 136.89286804]]
80 Cost:  11.3001 
Prediction:
 [[ 155.39256287]
 [ 181.80601501

790 Cost:  7.96005 
Prediction:
 [[ 154.59620667]
 [ 182.35496521]
 [ 181.34643555]
 [ 198.30799866]
 [ 137.64982605]]
800 Cost:  7.92147 
Prediction:
 [[ 154.58605957]
 [ 182.36196899]
 [ 181.34338379]
 [ 198.30537415]
 [ 137.65937805]]
810 Cost:  7.88316 
Prediction:
 [[ 154.57594299]
 [ 182.36894226]
 [ 181.34033203]
 [ 198.30274963]
 [ 137.66886902]]
820 Cost:  7.84506 
Prediction:
 [[ 154.56587219]
 [ 182.37590027]
 [ 181.33729553]
 [ 198.30014038]
 [ 137.67834473]]
830 Cost:  7.80712 
Prediction:
 [[ 154.55580139]
 [ 182.38284302]
 [ 181.33427429]
 [ 198.29753113]
 [ 137.68780518]]
840 Cost:  7.76944 
Prediction:
 [[ 154.54574585]
 [ 182.38973999]
 [ 181.33123779]
 [ 198.29492188]
 [ 137.69720459]]
850 Cost:  7.73194 
Prediction:
 [[ 154.53575134]
 [ 182.39663696]
 [ 181.32821655]
 [ 198.29232788]
 [ 137.706604  ]]
860 Cost:  7.69462 
Prediction:
 [[ 154.52578735]
 [ 182.40353394]
 [ 181.32522583]
 [ 198.2897644 ]
 [ 137.71600342]]
870 Cost:  7.65755 
Prediction:
 [[ 154.51583862

1580 Cost:  5.47266 
Prediction:
 [[ 153.87530518]
 [ 182.85243225]
 [ 181.12968445]
 [ 198.11882019]
 [ 138.33000183]]
1590 Cost:  5.4474 
Prediction:
 [[ 153.86714172]
 [ 182.858078  ]
 [ 181.12724304]
 [ 198.11665344]
 [ 138.3377533 ]]
1600 Cost:  5.42237 
Prediction:
 [[ 153.85902405]
 [ 182.86367798]
 [ 181.12480164]
 [ 198.11448669]
 [ 138.34544373]]
1610 Cost:  5.39742 
Prediction:
 [[ 153.85090637]
 [ 182.86927795]
 [ 181.12237549]
 [ 198.11231995]
 [ 138.35313416]]
1620 Cost:  5.37255 
Prediction:
 [[ 153.84281921]
 [ 182.87487793]
 [ 181.11994934]
 [ 198.1101532 ]
 [ 138.36082458]]
1630 Cost:  5.34788 
Prediction:
 [[ 153.83476257]
 [ 182.88044739]
 [ 181.11753845]
 [ 198.10801697]
 [ 138.3684845 ]]
1640 Cost:  5.32332 
Prediction:
 [[ 153.82670593]
 [ 182.88598633]
 [ 181.1151123 ]
 [ 198.10583496]
 [ 138.37609863]]
1650 Cost:  5.29889 
Prediction:
 [[ 153.81869507]
 [ 182.89154053]
 [ 181.11271667]
 [ 198.10369873]
 [ 138.38371277]]
1660 Cost:  5.27462 
Prediction:
 [[ 153.