In [1]:
import numpy as np

In [11]:
xy = np.loadtxt('data/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(xy)
print(x_data)
print(y_data)

[[  73.   80.   75.  152.]
 [  93.   88.   93.  185.]
 [  89.   91.   90.  180.]
 [  96.   98.  100.  196.]
 [  73.   66.   70.  142.]
 [  53.   46.   55.  101.]]
[[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]]
[[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]]
